config/routes.rb
Inventory::Application.routes.draw do
  resources :users, :only => ['new', 'create']
  resources :sessions, :only => ['new', 'create', 'destroy']
  resources :welcome, :only => ['index']

  get 'sign_in' => 'sessions#new', :as => :sign_in
  get 'sign_out' => 'sessions#destroy', :as => :sign_out

  root :to => 'products#index'

  resources :products do
    collection do
      get :phone
    end
  end

  get 'phone' => 'products#phone'
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => '300x300' },
                            :storage => :s3,
                            :s3_credentials => S3_CREDENTIALS,
                            :bucket => S3_BUCKET,
                            :path => "images/:id/:style.:extension"

  CATEGORIES = ['Necklace', 'Bracelet', 'Earring', 'Ring', 'Hair Accessories']
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_secure_password
  validates_presence_of :password, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
#  force_ssl

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  inherit_resources

  def phone
    @products = Product.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by_email(params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash[:error] = "Invalid email or password"
      @user = User.new(:email => params[:user][:email]) # keep email in form to try again
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Signed Up!"
    else
      render "new"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Inventory
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    /[if lt IE 7]
      = stylesheet_link_tag "ie"
    = javascript_tag "$(document).ready(function () {#{yield(:js)};})"
    = csrf_meta_tags
  %body
    #main
      #session_nav
        -if current_user.present?
          %ol
            %li=link_to 'Sign Out', sign_out_path
        -else
          %ol
            %li=link_to 'Sign In', sign_in_path
            %li=link_to 'Sign Up', new_user_path
      .clear
      #notices
        -if flash[:notice].present?
          .notice
            notice:
            =flash[:notice]
        -if flash[:error].present?
          .error
            error:
            =flash[:error]
      .clear
      = yield
      .clear

app/views/products/_form.html.haml
=semantic_form_for @product, :html => {:multipart => true} do |f|
  =f.input :name
  =f.input :category, :as => :select, :collection => Product::CATEGORIES
  -if @product.image.present?
    Current Image:
    =link_to "#{@product.image_file_name} (View)", @product.image.url
    =f.input :image, :as => :file, :label => "Change Image"
  -else
    =f.input :image, :as => :file
  =f.submit

app/views/products/edit.html.haml
%p=link_to 'Return to Products', products_path
%h1 Edit Product
=render 'form'

app/views/products/index.html.haml
%h1 Manage Products

%p=link_to 'Add Product', new_product_path

%table
  %tr
    %th ID
    %th Name
    %th Category
    %th Image
    %th Actions
  -@products.each do |product|
    %tr
      %td=product.id
      %td=product.name
      %td=product.category
      %td=product.image.present? ? 'Present' : 'No Image'
      %td
        =link_to 'Edit', edit_product_path(product)
        \|
        =link_to 'Show', product_path(product)
        \|
        =link_to 'Destroy', product_path(product), :confirm => 'Are you sure', :method => 'delete'

app/views/products/iphone.html.haml
.product_list
  -@products.each do |product|
    .product
      .name=product.name
      .image=image_tag product.image.url(:medium), :width => 300
  .clear

app/views/products/new.html.haml
%p=link_to 'Return to Products', products_path
%h1 New Product
=render 'form'

app/views/products/phone.html.haml
.product_list
  -@products.each do |product|
    .product
      .name=product.name
      .image=image_tag product.image.url(:medium)
  .clear

-content_for :js do
  p=new ProductPicker();

app/views/products/show.html.haml
%p=link_to 'Return to Products', products_path
%h1=@product.name
%p
  Category:
  =@product.category
%p
  -if @product.image.present?
    =image_tag @product.image.url
  -else
    No image set

app/views/users/new.html.haml
%h1 Sign Up

=semantic_form_for @user do |f|
  =f.input :email
  =f.input :password
  =f.input :password_confirmation
  =f.submit

app/views/welcome/index.html.haml
%p Put your content here!

%p Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.